---
#infoblox username
username:
#infoblox passwd
password:
#Infoblox api host
host:
#infoblox api version
:wapi_version: '2.0'
#Use  pre-definded ranges in networks to find available IP's (requires restart to take affect)
:range: false
